### ISSUE TITLE
<input data-nativekeyboard="true" type="text"  /> not working

### ISSUE THREAD

**Issue by mralj** [EddyVerbruggen/cordova-plugin-native-keyboard#101]
Hello,
 
I am interested in purchasing this plugin to use in our Cordova app. 
I have tired out this feature:

`<input data-nativekeyboard="true" type="text" value="max 15 chars" maxlength="15" style="font-size:13px; font-family:Helvetica; font-style:italic" />`

As shown on [index_all_features.html](https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/blob/master/demo/index_all_features.html). 
But it is not working for us. I have tried it on pretty basic html "page", and there are no other keyboard plugins in project.

I have tried this on Android 9.0, Google Pixel 3 device. Is this not supposed to work yet or am I missing something ?

**Comment by EddyVerbruggen** [comment]
That's not documented in the readme, so not supported.
