### ISSUE TITLE
Textinput disappears when using "secure: true"

### ISSUE THREAD

**Issue by mariusbolik** [EddyVerbruggen/cordova-plugin-native-keyboard#104]
Hey Eddy,

thank you for this awesome Plugin :D
But I have one small problem. If I set the "secure" option to "true", the Textfield hides behind the keyboard after the first letter was entered. So I have to click anywhere on the screen to make the Keyboard disappear. Then I have to klick the Textinput at the bottom of the screen again to continue using you plugin.

Best Regards
Marius

**Comment by wuori** [comment]
I'm having this same issue even without the `secure` option. Can't seem to figure it out. iOS only, Android works fine.

**Comment by wuori** [comment]
@mariusbolik I was able to get this working by just returning out of the `shrinkViewKeyboardWillChangeFrame` method in `CDVNativeKeyboard.m` before it executes anything. Weird... but it works.
