### ISSUE TITLE
invalid license on iOS 13

### ISSUE THREAD

**Issue by wo-github** [EddyVerbruggen/cordova-plugin-native-keyboard#105]
On iOS 13 the license is invalid after 5min. The same App runs on iOS 12 and 11 without problems.
If I run the App on iOS 11 oder 12 simulator, everything is fine and the plugin works more then 5min. But if I run the same App on a iPhone 8 with iOS 13  simulator, the plugin told me after 5min, that the licence isn`t valid.
It happens with version 1.5.7 and with the newest version 2.0.3.

**Comment by EddyVerbruggen** [comment]
OK, this is unfortunate. Apple changed an internal method implementation in iOS 13 (specifically the `NSData` class) which meant the on-device license check failed.

I believe this only affects apps built with Xcode 11.

Please update to 2.0.4 which should fix the problem. Sorry for any inconvenience this caused!
