### ISSUE TITLE
Wrong Default Font when building with Xcode 11

### ISSUE THREAD

**Issue by erikramalho** [EddyVerbruggen/cordova-plugin-native-keyboard#106]
After we updated to Xcode 11 and build our app, Native Keyboard is using a different font family.  

Here are some pics with the previous font and the new one after build using Xcode 11.

![IMG_5346](https://user-images.githubusercontent.com/5274068/65890542-6bc2fe80-e379-11e9-835b-56df8a8b5ade.jpg)
![IMG_5348](https://user-images.githubusercontent.com/5274068/65890560-7087b280-e379-11e9-85c3-61c1e7a26209.jpg)

I google it and found some issues related to it:
https://stackoverflow.com/questions/56470421/font-style-gets-changed-issue-in-xcode-11-beta
https://stackoverflow.com/questions/56524375/custom-font-none-installed-xcode-11-beta

**Comment by erikramalho** [comment]
It seems if you add this line 
` self.textView.font = [UIFont fontWithName:@"Helvetica" size: 15];`
to NKSLKTextViewController.h seems to solve the problem. I'm no expert with Xcode, not sure if it's the right approach.

Waiting for you feedback @EddyVerbruggen ;-)

**Comment by EddyVerbruggen** [comment]
Interestingly, that's almost exactly what I just did ;)
I wish I read your comment earlier.

**Comment by EddyVerbruggen** [comment]
To my 👁"Helvetica Neue" at size 16 was most similar to the old font (of iOS 12), so rolling that now.. please update to 2.0.5. And thanks for the very clear bug report and that suggestion.
