### ISSUE TITLE
Apple compliance - ITMS-90809 UIWebView

### ISSUE THREAD

**Issue by pcvengros** [EddyVerbruggen/cordova-plugin-native-keyboard#109]
Hello,

Apple started to notify developers regarding migration from UIWebView to WKWebView. As of April 2020 they will not accept apps using UIWebView.

Last occurence of UIWebView use in our app is in this plugin. Please check and modify to use WKWebView. Thanks

Apple message:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by EddyVerbruggen** [comment]
@pcvengros Thanks for the heads-up.

Do you know if [this line](https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/blob/419ce96744ab05c8b23319bc7de9e2c8a6ca4cce/src/ios/NKSLKTextViewController.m#L55) is the only occurrence (or don't they report that)?

**Comment by EddyVerbruggen** [comment]
I've removed `UIWebView` from the aforementioned piece of code and published 2.0.6.

If you find any other spots, let me know.

**Comment by EddyVerbruggen** [comment]
Rumour has it that this deprecation is postponed to december 2020 (🦠): https://twitter.com/kythanh/status/1238025571105308673?s=20

**Comment by JamesPeck** [comment]
They are accepting new Apps using UIWebView until 4/1/2020 but you can update existing apps until December 2020.
