### ISSUE TITLE
Font Awesome setting crashes app

### ISSUE THREAD

**Issue by timbo1437** [EddyVerbruggen/cordova-plugin-native-keyboard#111]
When changing the type: 'fontawesome' the app instantly crashes when starting to open the keyboard.

```js
{
  type: 'fontawesome', // or 'text', 'system, 'fontawesome'
  value: 'fa-thumbs-up', // http://ionicons.com/, right-click and inspect the :before value
  color: '#ffffff', // default '#ffffff'
  fontSize: 22, // default 22
  callback: function() {console.log('Thumbs Up button pressed');}
}
```

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
```

I have tried several values, and still the same crash.

**Comment by EddyVerbruggen** [comment]
That's strange, I just tried with `fa-camera` and it worked. Might be a build environment issue due to a missing fontawesome font file or something.. can you try cleaning the /platforms/ios folder and build again? I tried on a real device btw (not a simulator).

If the problem persist, please share the entire snippet so I can recreate.

**Comment by timbo1437** [comment]
I tried cleaning the builder folder, and I tried removing the platform and adding the platform back, still getting the same error.  I tried with `fa-camera` also.

Xcode: 11.4.1
iOS: 13.4.1
Cordova: 9.0.0

I'm gonna try a fresh cordova install with no plugins to see if I can get it to work, and if not then I will post the entire error.

**Comment by timbo1437** [comment]
So this is obviously an error with a plugin or something else maybe in my hooks, but it's not your plugin. Works perfectly with a fresh install, I should have done that before opening an issue.. Great job on this, and sorry to have wasted your time. Closing this issue.

Side note:  I sent a few emails to your gmail and I haven't heard back, not sure if it's going to spam or not, or if you are just swamped with emails. :). If you don't have those emails please contact me tim at dotedison.com. Thanks!

**Comment by EddyVerbruggen** [comment]
Hey Tim, happy to see that helped!

I actually did receive your mail but wanted to make sure this issue was tackled first 😉 - will get on it now.
