### ISSUE TITLE
Dead mans switch for source code

### ISSUE THREAD

**Issue by jpike88** [EddyVerbruggen/cordova-plugin-native-keyboard#116]
Is there some sort of mechanism which will enable full access to the source code in the case you're 'hit by a bus'? I've had to push back again with my employees regarding this plugin due to my doubts raised in #115, and it's a shame... but I'm just ensuring we aren't stuck with a pile of obfuscated code for such a critical component.

**Comment by EddyVerbruggen** [comment]
Yes there is. My colleague has access to all my stuff in (in this case) my Bitbucket repos and will make it a public repo in case of this kind of trouble. Likewise the other way around. And no, we're not planning on being hit by the same bus simultaneously.

I'd also be happy to give you a copy of the current sources if you email me directly.
