### ISSUE TITLE
Error using it with Capacitor

### ISSUE THREAD

**Issue by Exocomp** [EddyVerbruggen/cordova-plugin-native-keyboard#117]
I get the following error during compile, let me know what you need to troubleshoot:

`CDVNativeKeyboard.m:137:75: No visible @interface for 'CDVViewController' declares the selector 'parseInterfaceOrientations:'`

```
  NSArray * ors = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"UISupportedInterfaceOrientations"];
  NSArray * suppOrientations = [((CDVViewController*)self.viewController) parseInterfaceOrientations:ors];
  [tvc setSupportedInterfaceOrientations:suppOrientations];
```

**Comment by EddyVerbruggen** [comment]
Yeah, it's a Cordova plugin (`CDVViewController` = Cordova View Controller), so I can imagine this is the case.

**Comment by Exocomp** [comment]
Not the response I was expecting because Cordova plugins can be used with Capacitor, however if you already knew that and still choose not to do anything then alright.

**Comment by EddyVerbruggen** [comment]
Wow. Ok. IDK man, I’ve never used Capacitor.
