### ISSUE TITLE
Question: can we use native keyboard as simple keyboard, with shrink view animation

### ISSUE THREAD

**Issue by Aarbel** [EddyVerbruggen/cordova-plugin-native-keyboard#118]
I'm using https://github.com/cjpearson/cordova-plugin-keyboard/issues for the moment.

Big drawbacks: the library is not well maintained, and the library doesn't handle viewport animation when keyboard opens. The result is really glitchy. Cf https://github.com/cjpearson/cordova-plugin-keyboard/pull/22

Is that possible to do it simply with this library, without particularly using the "native" keyboard features ?

Thanks a lot for your work !

**Comment by Aarbel** [comment]
@EddyVerbruggen no infos about this ?  Thanks a lot !

**Comment by EddyVerbruggen** [comment]
IDK exactly what you mean, but why nut install the trial and see for yourself?

**Comment by Aarbel** [comment]
@EddyVerbruggen 
1 - is that possible to use a normal keyboard with your plugin ? (and not field and special keyboards)
2 - when the keyboard opens, what behaves for the webview ? Is that shrinked or centered ? (on iOS basic behavior is to center view, which causes bad ergonomy behaviors). If it's the case, is the height shrink is animated ?

Problem with other plugin is that the webview shrink is not animated, cf this example:
![image](https://user-images.githubusercontent.com/25119847/89126257-a428f100-d4e4-11ea-9b1c-0f1b84725c5f.png)

Thanks a lot for your tips  ! (No time for the moment to test the plugin 3 hours).

**Comment by Aarbel** [comment]
@EddyVerbruggen any news about it ? Thanks a lot for your help !

**Comment by Aarbel** [comment]
@EddyVerbruggen 

my exact question is, can we remove the text / buttons bar inside your keyboard ?

![image](https://user-images.githubusercontent.com/25119847/91437783-b5a6b400-e86a-11ea-8428-9b6b9918a70d.png)

**Comment by Aarbel** [comment]
@EddyVerbruggen ?

**Comment by EddyVerbruggen** [comment]
Nope you can't as the native lib being used doesn't support it.
