### ISSUE TITLE
Feature Request to add an onKeyboardWillHide callback function

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-native-keyboard#12]
I am using the **onKeyboardDidHide** function to trigger the resizing of a  list which appears on the same page as the native keyboard control. My app appears somewhat “choppy” because too much time elapses between the time the keyboard is minimized and the time the **onKeyboardDidHide** function is invoked. It would appear much smoother if there was an **onKeyboardWillHide** function that is invoked prior to the keyboard minimizing so I can start resizing the list sooner. 

BTW - The **cordova-plugin-keyboard** plugin has both an **onKeyboardWillHide** and an **onKeyboardWillShow** callback.

Thanks

**Comment by EddyVerbruggen** [comment]
`onKeyboardWillHide` has been added for iOS (cordova-plugin-keyboard also only supports iOS). If you're using `UIWebView` (not tested with `WKWebView`) then it should work fine with 1.1.5.

**Comment by DaveRand** [comment]
Hi Eddy,

I must have forgotten or never realized that 
cordova-plugin-keyboard only supported iOS. I am 
currently using UIWebView. I will test it later today.

Thanks


At 01:17 AM 12/30/2016, you wrote:

**Comment by DaveRand** [comment]
Thanks Eddy. I just tested the new plugin. 
Resizing my list when the new onKeyboardWillHide 
function is called looks so much smoother now when the keyboard is hidden.


At 01:17 AM 12/30/2016, you wrote:

**Comment by DaveRand** [comment]
Hi Eddy,

I posted another feature request today. After 
implementing the new onKeyboardWillHide function 
and getting a much faster responsive time, it has 
become apparent that the response time when 
showing the keyboard is now too slow when I 
resize my list. The reason is because I am 
waiting for the onKeyboardDidShow function to be 
called before resizing my list. Originally, the 
response time after showing the keyboard did not 
seem too bad when compared to the hiding time. 
But now that I am using the onKeyboardWillHide 
function, it has become apparent that the 
response time to resize my list is too slow when 
waiting for the onKeyboardDidShow function to be called.

Happy New Year!

Thanks


At 01:17 AM 12/30/2016, you wrote:
