### ISSUE TITLE
Changing the color of the outline around the input

### ISSUE THREAD

**Issue by ajoslin** [EddyVerbruggen/cordova-plugin-native-keyboard#15]
My app is themed very dark, with black everywhere: [Screenshot](http://ajoslin.co/xgrq/iAPDGzBz)     

The one color I can't customize with the currently available options is the outline around the native text input (as seen in the screenshot, it's still set to a light grey).

Can an option be added to allow this outline color to be changed?

Thanks for the fantastic library, by the way. I've purchased a license and will probably purchase more for future apps I create.

**Comment by ajoslin** [comment]
Here's my current configuration when opening the keyboard:

```js
  window.NativeKeyboard.showMessenger({
    onSubmit,
    onKeyboardWillShow,
    onKeyboardWillHide,
    onTextChanged,
    animated: true,
    keepOpenAfterSubmit: true,
    appearance: 'dark',
    placeholder: capitalize(state.theme.title()),
    placeholderColor: '#808080',
    backgroundColor: '#010101',
    textViewBackgroundColor: '#000000',
    caretColor: '#ffffff',
    textColor: '#ffffff',
    leftButton: {
      type: 'ionicon',
      value: '\uf48a',
      color: '#ffffff',
      onPress: onPressUpload
    },
    rightButton: {
      type: 'text',
      value: 'Send',
      color: '#ffffff'
    }
  })
```

**Comment by EddyVerbruggen** [comment]
Turns out I've already exposed that as a property :)

Just didn't document it yet (will do right away).

Set `textViewBorderColor: '#000000'` and behold!

**Comment by ajoslin** [comment]
Fantastic, thanks.
