### ISSUE TITLE
the "rightButton" behavior

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-native-keyboard#20]
hi @EddyVerbruggen 
awesome new plugin

Android 6.0.1

[default behavior]
when I call "showMessenger" and use these option
`
var options = {
text: "", 
placeholder: 'some word...', 
};
`
the keyboard show up
at the moment，the "rightButton" will not show up until I type some words in the message column (>0 word)

[suggestion behavior]
when I call "showMessenger" and use these option
`
var options = {
text: "there have some default words", 
placeholder: 'some word...', 
};
`
the keyboard show up
at the moment，the message column have some default words already，but it still must type some words and the "rightButton" will show up，I suggest if the text have some default words already，just Direct display the "rightButton"

**Comment by EddyVerbruggen** [comment]
Not a bad idea. But consider this: I added the prefill option for cases where you want to edit an existing piece of text and thought it wouldn't make sense to be able to submit the result if nothing was changed. Perhaps that's a bit too over-engineered.

Anyone else has an opinion on this?

**Comment by EddyVerbruggen** [comment]
The rightbutton is now aligned with iOS regarding this behaviour: if you prefill text the 'send' button will be enabled.

**Comment by frey1esm** [comment]
Shouldn't the right send button always be visible, or at least configurable? Having a text input box with no send button visible is odd, even when empty. Chat apps like WhatsApp & Skype have other buttons (i.e. microphone, camera) visible until there is text input, then they replace it with the send button.
