### ISSUE TITLE
iOS text selection dot clipped while touching screen

### ISSUE THREAD

**Issue by vbraun** [EddyVerbruggen/cordova-plugin-native-keyboard#25]
Steps to reproduce:

* Enter text on iOS
* Select a range of text
* Touch screen in selected range, as if to move the blue start or end marker 

Result:
* The blue dots at the range start/end markers are clipped by the text box while the screen is touched

Expected result:
* The blue dots are not clipped, just as when the screen is not touched

![img_5618](https://cloud.githubusercontent.com/assets/888729/23411685/5a475b4e-fdd3-11e6-8b86-cddd68bdedd4.PNG)

**Comment by EddyVerbruggen** [comment]
Lol, that's an interesting find. Not entirely sure I can do much about that but let's keep this open.

**Comment by vbraun** [comment]
To clarify, the screenshot was made while touching the screen (which is why the magnifying glass for the cursor position is shown)

**Comment by EddyVerbruggen** [comment]
Do you have the Slack app for iOS? It has the exact same issue. That makes sense because this plugin wraps the [SlackTextViewController](https://github.com/slackhq/SlackTextViewController) library.

Would you mind opening an issue there instead?
