### ISSUE TITLE
Selecting "Format" from the iOS copy/paste context menu breaks context menu

### ISSUE THREAD

**Issue by vbraun** [EddyVerbruggen/cordova-plugin-native-keyboard#26]
Steps to reproduce
-------------------------
* Enter text (iOS)
* Long press on word
* Pick "select" from the context menu to select word
* The extended Cut/Copy/Paste/Replace.../Look Up/Share../Format context menu appears
* Pick the "Format" option
* Press the "Send" button

Result
---------
Send (right button) does not perform any action any more, neither does the plus-button (left button).

Expected result
--------------------
There probably shouldn't be a "Format" option in the menu to start with.

**Comment by vbraun** [comment]
Picture of the "Format" menu option:

![image1 3](https://cloud.githubusercontent.com/assets/888729/23412021/8b49c6ae-fdd4-11e6-816c-0040a1d92785.PNG)

**Comment by vbraun** [comment]
As for #25, the blue dots are only clipped while the finger is touching the screen. The screenshot here is while not touching the screen.

**Comment by EddyVerbruggen** [comment]
I tried the 'Format' key on both an iOS 10 sim and iOS 9 device and couldn't reproduce the issue unfortunately. What's you device?

Does the format function change anything visually when applied in your case?

**Comment by EddyVerbruggen** [comment]
`Format` has been removed in 1.3.1.

**Comment by vbraun** [comment]
Device is an iPhone 6s, language set to German (could be the reason why the format types menu does not show up)

The format button is working in the Slack app, for the record
