### ISSUE TITLE
Keyboard doesn't obey 'auto capitalize' global setting on Android

### ISSUE THREAD

**Issue by kshaaban-** [EddyVerbruggen/cordova-plugin-native-keyboard#27]
On Android devices, the keyboard does not obey the global device setting for capitalizing first letters of sentences (as can also be seen from the awesome GIFs in the README :))

**Comment by EddyVerbruggen** [comment]
Interesting one, can you show me what and where you specified that global setting please?

**Comment by kshaaban-** [comment]
Absolutely!

These flows are from a Nexus 5 running 6.0.1 (though it'll probably be very similar on other android devices)

#### Device Settings Flow:
1. Settings
2. Language & Input
3. Keyboard & input methods
4. Select your keyboard
5. Text correction
6. Auto capitalization


#### From the keyboard presented by the plugin
1. Keyboard Settings (on a nexus the comes from a little arrow next to the word suggestions, in the animated GIF in the readme, it seems to be a button in the bottom right?)
    - this takes me to the outcome of step 4 in the previous flow
2. Text correction
3. Auto capitalization

**Comment by EddyVerbruggen** [comment]
Thanks for the details on how to observe this issue.

I noticed that apps like Twitter (the search function) and the Google search gadget on the home screen also don't obey the setting.

That being said, it makes sense to obey it so in 1.3.1 it will!
