### ISSUE TITLE
Keyboard show/hide events fire when the orientation changes

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-native-keyboard#30]
Hi Eddy,

The following events fire when the input bar and keyboard are visible and the device orientation changes to landscape or portrait:

onKeyboardWillHide, onKeyboardDidHide, onKeyboardWillShow and onKeyboardDidShow

The keyboard remains visible when the orientation is changed. These events do not fire when you change the orientation while the input bar is visible and the keyboard is hidden. Was this intentional?

**Comment by EddyVerbruggen** [comment]
I think that's just what iOS does for us; it has to actually change the keyboard layout to accomodate for the changed size. I've seen this with other keyboard plugins as well. Not intentional, just passing on what iOS triggers.
