### ISSUE TITLE
The hideKeyboard method does not close the keyboard on Android

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-native-keyboard#32]
The **hideKeyboard** method does not work on Android devices.

**Comment by EddyVerbruggen** [comment]
Did you see this on a specific device, or a few differt ones? I'll test it on my Nexus 6P running Android 7 first.

**Comment by DaveRand** [comment]
It consistently failed for me on the following Android devices:

HTC One Mini (Android 4.4.2)
LG G-Pad 7.0 LTE (Android 5.0.2)
Google Nexus 6P (Android 7.1.1)


Thanks


At 10:07 AM 3/15/2017, you wrote:

**Comment by EddyVerbruggen** [comment]
Do you actually use (the non-existing) `hideKeyboard` function, or `hideMessenger`? I just tested the latter and that works fine on my Nexus 6P.

**Comment by DaveRand** [comment]
I am using the hideKeyboard function which just 
hides the keyboard and retains the text input bar 
at the bottom. hideMessenger works fine for me 
too, but it also hides the text input bar.

Thanks


At 12:58 AM 3/16/2017, you wrote:

**Comment by EddyVerbruggen** [comment]
Please use the new `hideMessengerKeyboard` feature as [documented here](https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard#hidemessengerkeyboard). It's now available from npm when updating to 1.3.2.

**Comment by DaveRand** [comment]
Great thanks!

I will try it out.


At 01:17 PM 3/16/2017, you wrote:
