### ISSUE TITLE
JS Unexpected plugin result: {"contentHeight":31,"contentHeightDiff":0}

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-native-keyboard#33]
Hi Eddy,

I thought I should report this error/warning message which I've been getting ever since I started using the plugin. It never caused any issues that I am aware of so I never reported it. I thought I should report it now just in case it is related to another issue.

I get the following error from **NativeKeyboard.js** when I tap on the input text bar to open the keyboard:

**JS Unexpected plugin result: {"contentHeight":31,"contentHeightDiff":0}**

I also get the same exact error when I close the keyboard using the Android back button. I have definitely seen the error in both Android and iOS, but right now it only seems to be happening in Android.

Thanks

**Comment by EddyVerbruggen** [comment]
Thanks. It's a bit of a friendly development-time error I should remove with the shipped product. Shouldn't affect usage in any way 👍
