### ISSUE TITLE
Need the height of the text input bar when the keyboard is closed

### ISSUE THREAD

**Issue by DaveRand** [EddyVerbruggen/cordova-plugin-native-keyboard#35]
Hi Eddy,

The text input bar is rendering a different height depending on what type of Android device it is running on. For example, the height might be 64 pixels on one device and 84 pixels on another. The text input bar is always the same height on every iOS device I have tested.

The only place the plugin returns a height is when the **onKeyboardWillShow** and **onKeyboardDidShow** events are called, but this height includes the height of the keyboard.

Can you return the height of the text input bar without the keyboard height in a new event that is fired when the **showMessenger** method is called? Or maybe add a new method which just returns the text input bar height? Does this make sense?

Thanks

**Comment by DaveRand** [comment]
I am no longer encountering this issue where the input text bar has varying heights on different Android devices. I am closing the issue for now.

**Comment by DaveRand** [comment]
Sorry Eddy. The text input bar is in fact rendering a different height depending on the Android device it is running on. Please read my original comments above.

Thanks

**Comment by HartHerbert** [comment]
👍

**Comment by robin-huss** [comment]
@EddyVerbruggen any chance you can look into this issue? I also ran into this on a Android device:

Name: Wiko_Sunny_3_Mini
hw.lcd.width: 480
hw.lcd.height: 854
hw.lcd.density: 240

Using a emulator i found that all elements in the text input bar are 32px higher than expected compared to other Android devices running our app.

**Comment by EddyVerbruggen** [comment]
@robin-huss Is there a way to test this without having the device you mentioned? Perhaps you are aware of two different simulator configs that report a different height for the messenger bar? I'd be happy to look into it, but I need a decent way to reproduce the issue (and test a fix).

**Comment by robin-huss** [comment]
I ended up checking it in a simulator: it shows the same issue as on the real device. I'm not sure how to export emulator configs. I found some configuration options in the config.ini file. Does that help?

AvdId=Wiko_Sunny_3_Mini
PlayStore.enabled=false
abi.type=x86
avd.ini.displayname=Wiko Sunny 3 Mini
avd.ini.encoding=UTF-8
disk.dataPartition.size=800M
fastboot.forceColdBoot=no
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.camera.back=emulated
hw.camera.front=emulated
hw.cpu.arch=x86
hw.cpu.ncore=2
hw.dPad=no
hw.device.hash2=MD5:5d160e07cfd9f323c2e7329cc6ba18a0
hw.device.manufacturer=User
hw.device.name=Wiko Sunny 3 Mini
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=auto
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=240
hw.lcd.height=854
hw.lcd.width=480
hw.mainKeys=no
hw.ramSize=512
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images\android-28\google_apis\x86\
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=100M
showDeviceFrame=no
skin.dynamic=yes
skin.name=480x854
skin.path=_no_skin
skin.path.backup=_no_skin
tag.display=Google APIs
tag.id=google_apis
vm.heapSize=48

**Comment by EddyVerbruggen** [comment]
Thanks, do you also have a repo I can clone to see the actual problem?

**Comment by robin-huss** [comment]
Unfortunately the repo containing our app is private and i am not allowed to share it. I'll try and get some screenshots in a minute.

**Comment by robin-huss** [comment]
1. Input bar is the expected size:
![input_bar_normal](https://user-images.githubusercontent.com/26572475/53901363-1ae76380-403f-11e9-8871-ba1a0e109d5c.png)
2. Input bar height is taller than expected, overlapping the last message:
![input_bar_to_big](https://user-images.githubusercontent.com/26572475/53901365-1ae76380-403f-11e9-8f29-694a4c9ffd44.png)

**Comment by EddyVerbruggen** [comment]
Thanks. Please enlighten me, how do you go from screenshot 1 to 2? Is that the same app running on the same device, or two different ones (which)?

**Comment by robin-huss** [comment]
It is the same app running on two different devices. You might have missed my edit: i included the AVD config in the detail tags above the corresponding screenshot.

**Comment by EddyVerbruggen** [comment]
Available now from npm (2.0.2), see `onMessengerBarHeightChanged` in the README.

**Comment by robin-huss** [comment]
> Available now from npm (2.0.2), see `onMessengerBarHeightChanged` in the README.

Hi Eddy, thank you for the new release. I tried `onMessengerBarHeightChanged` and it does exactly what it says. As soon as the height of the MessengerBar changes i get the height using this event.

We might have misunderstood eachother though. What @DaveRand and i mean is that we do not know the height of the MessengerBar when the keyboard is initialised. This is no problem on iOS because it's always the same height. On Android however, this initial height differs. Because the exact height is unknown we cannot adjust styling or other functionality accordingly.

It might not match with the event's name, but if `onMessengerBarHeightChanged` would fire on initialise as well then we always know the height of the MessengerBar and our problem is solved!

Please let me know if anything is unclear!

**Comment by EddyVerbruggen** [comment]
@robin-huss Give 2.0.3 a shot, it should fire when initializing.

**Comment by robin-huss** [comment]
> @robin-huss Give 2.0.3 a shot, it should fire when initializing.

@EddyVerbruggen thank you for the update. Unfortunately i do not see the `onMessengerBarHeightChanged` event triggering on initialise. The event is still triggered when the height of the messenger bar changes (for instance when i type more then 1 row of text).

Is there a setting or condition needed to be met in order for this event to triger on initialise?

**Comment by EddyVerbruggen** [comment]
Perhaps our definitions of 'initialise' are not the same.

**Comment by robin-huss** [comment]
Hi @EddyVerbruggen, our definitions are the same. I made a mistake on my part. The event does fire and we were able to fix our problem.

Thank you very much for the effort!
