### ISSUE TITLE
Send Image and Text

### ISSUE THREAD

**Issue by josaal17** [EddyVerbruggen/cordova-plugin-native-keyboard#39]
My question is if with this plugin I can send multimedia with text, in the same message. Similar to Whatsapp, that when I choose the image or video can write a message.

And if it's impossible any idea or plugin that how implement with cordova

Thanks

**Comment by EddyVerbruggen** [comment]
That's not built in, but you could have the user upload the photo, then require him to enter some text (perhaps a `prompt`) and then send it.
