### ISSUE TITLE
Incompatible with cordova-plugin-admob-free

### ISSUE THREAD

**Issue by s-hinze** [EddyVerbruggen/cordova-plugin-native-keyboard#40]
When I want to monetize my App with AdMob and use this Plugin, only the Banner-Ad from AdMob will be shown after calling NativeKeyboard.showMessenger.

![bildschirmfoto_2017-05-04_10-20-39](https://cloud.githubusercontent.com/assets/25742551/25695482/956a5d9e-30b3-11e7-888d-271795ea6aaf.png)

It is reproducable with all free AdMob Plugins for Cordova.
Looks like NativeKeyboard shrinks the WebView of my App to 0px.

Additional:
The AdMob Plugin creates new WebViews to display the Ads.

**Comment by EddyVerbruggen** [comment]
Ah, interesting. Is that on Android only?

Also, is there a repo I can clone to reproduce this perhaps?

**Comment by s-hinze** [comment]
On iOS you can use it as normal, but when I close the messenger, the AdMob-Banner will turn into grey. 
I think the same Issue as on Android but other WebView (from AdMob).

![ohne titel kopie](https://cloud.githubusercontent.com/assets/25742551/25698641/e88aacd4-30bf-11e7-81dc-b8e9774143c3.png)

I don't have a public repo at the moment.
But I can create one today, if needed.

**Comment by EddyVerbruggen** [comment]
I've tried my best this weekend making this more compatible with plugins like AdMob. Please give 1.4.0 a spin and let me know how it goes.

**Comment by s-hinze** [comment]
Thanks for you'r work.
On Android everything works fine now with this Version and AdMob.

On iOS (tested on 10.3.1) the Native Keyboard hides behind the keyboard and the View of my App still turns into grey.

![img_1254](https://cloud.githubusercontent.com/assets/25742551/26045557/1c60e882-394b-11e7-9319-5974cd236f99.PNG)

Let me know if you can reproduce this Issue.
If not, i will create a repo for you.

**Comment by EddyVerbruggen** [comment]
I wasn't able to reproduce this. Can you try changing the `overlap` setting of the AdMob plugin and see if that makes any difference? I see a little difference that case, but with the updated plugin version I can't reproduce what you're showing here unfortunately.

**Comment by s-hinze** [comment]
Changing the overlap setting wont help.

I created a repsitory for you.
https://github.com/s-hinze/native-keyboard-admob
(Maybe a bug of NativeKeyboard + AdMob + Ionic2 ?)

**Comment by EddyVerbruggen** [comment]
Thanks. When I clone that repo, what are the commands I need to execute to reprouce the issue exactly? `git clone <repo>` etc..

**Comment by s-hinze** [comment]
First you need Ionic `npm i -g ionic cordova`

1. `git clone https://github.com/s-hinze/native-keyboard-admob.git`
2. `npm install`
3. `ionic platform add ios`
4. `ionic run ios`

**Comment by EddyVerbruggen** [comment]
Hey @s-hinze that repo has the banner overlapping on the bottom - that's the same place where the keyboard is displayed, so it's behind the banner. What do you expect the layout to be when both the banner (with overlay=true) and the keyboard are shown?

**Comment by s-hinze** [comment]
Hi Eddy,
the problem is still alive with android. I try Version 1.3.2, 1.4.0, 1.4.1. It looks like on iOS, the Keyboard open, but the rest of the content disappears and you only see a black surface.

![screenshot_20170522-092951](https://cloud.githubusercontent.com/assets/25742551/26297151/f4bfec9c-3ed1-11e7-8267-54b982ae1836.png)

**Comment by EddyVerbruggen** [comment]
Hang on. You say iOS, but the pics are from Android. Can you please edit the previous comment to avoid confusion? Thx!

**Comment by s-hinze** [comment]
The problem with the black screen is on Android and iOS.

**Comment by EddyVerbruggen** [comment]
So that's with the exact code in `https://github.com/s-hinze/native-keyboard-admob.git` and the latest version of the plugin on both platforms?

**Comment by s-hinze** [comment]
No that happens in our current live app, the app is based on phonegap.

**Comment by EddyVerbruggen** [comment]
Did the problem go away with 1.4.1 in the `https://github.com/s-hinze/native-keyboard-admob.git` repo? If so, is there a way for me to reproduce the issue on your live app?

**Comment by s-hinze** [comment]
I try different version on iOS and Android. On iOS I have to use the 1.3.2 and on Android I have to use the 1.4.1
On iOS with Admob and version 1.4.1 there is no Keybaord visible, without initializing Admob, the keyboard is shown, as expected.

The firstview admob is active, with version 1.4.1
![v1 4 1 firstview](https://cloud.githubusercontent.com/assets/25742551/26482686/12d8bb4a-41e9-11e7-81fb-e9d19ed9ba30.png)

After try to open the keyboard, with version 1.4.1
![v1 4 1 afteropenkeyboard](https://cloud.githubusercontent.com/assets/25742551/26482697/25944ccc-41e9-11e7-9f08-f682b1af2e55.png)

version 1.4.1 without admob, it works
![v1 4 1 withoudadmob](https://cloud.githubusercontent.com/assets/25742551/26482716/3c8d6b98-41e9-11e7-9d90-290384dbefb2.png)

version 1.3.2 with admob, it works
![v1 3 2 withadmob](https://cloud.githubusercontent.com/assets/25742551/26482729/56745b84-41e9-11e7-9880-fa2d724b9502.png)

But the version 1.3.2 doesn`t work on Android, there is a black screen over the input field.

**Comment by wo-github** [comment]
The problem with admob plugin still exist. The issue isn`t closed. Do you try to fix the problem with the admob plugin?

**Comment by wo-github** [comment]
What about the problem with admob and this plugin on Android. Do you try to fix the problem with the admob plugin?
