### ISSUE TITLE
Ionic Project - Keyboard showing up after I hit the back button

### ISSUE THREAD

**Issue by jrmcdona** [EddyVerbruggen/cordova-plugin-native-keyboard#45]
Hey Eddy,

I added the keyboard plugin to my project today.  You can see in this video that after I go to my chat page, then hit the back button, the keyboard input is showing up on the previous page somehow.

Thanks

P.S. There are some issues with the scrolling I referenced in the https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/issues/28 post.  I can work on a simple repo to see if we can get to the bottom of these issues!

**Comment by jrmcdona** [comment]
Here is a better video:
https://1drv.ms/v/s!AnyXOztVClZYcw8NTWQofmqIImw

**Comment by EddyVerbruggen** [comment]
The native keyboard had no knowledge of your Ionic routes, or anything else that happens in the webview for that matter. So when navigating away from the chat page you should hide the keyboard programmatically, see https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard#hidemessenger

**Comment by jrmcdona** [comment]
Ok, will give that a try. Thanks

**Comment by jrmcdona** [comment]
I think what I will try to do is put the Keyboard functions in a service.  I have components within the page.  Component level is using some of the functions.   

Page level will be where I can hideMessenger once the page is going into ionViewWillLeave() life cycle event.

The service holding the keyboard functions can be injected into these.

See any issue there?

**Comment by jrmcdona** [comment]
Got it working with the service.  Looks good.

**Comment by aapiane09** [comment]
Did you have an issue with the keyboard pushing everything up after you've returned to a previous page? I get a white bar on the bottom (where the input bar used to be) which pushes all of the visuals up, but all links are still in their usual places (so you have to click slightly below an element if you want to go there.

![screen shot 2017-08-30 at 4 11 23 pm](https://user-images.githubusercontent.com/23176493/29899086-2fba16a4-8d9e-11e7-8db6-bf53c97102c2.png)

**Comment by jrmcdona** [comment]
No don't believe so.
