### ISSUE TITLE
how to use keyboard onKeyboardShow()

### ISSUE THREAD

**Issue by freezyh** [EddyVerbruggen/cordova-plugin-native-keyboard#47]
https://ionicframework.com/docs/native/keyboard/
the plugin keyboard of members  onKeyboardShow  is support androis ,but it not work,can you tell me how to use it, I will thanks you very much.

**Comment by FredeHo** [comment]
Don't get 
https://ionicframework.com/docs/native/native-keyboard/ (this repo) and https://ionicframework.com/docs/native/keyboard/ 
confused. 

This is native-keyboard so probably not the right spot for this issue. 

But anyway:
```
import { Keyboard } from '@ionic-native/keyboard';

constructor(private keyboard: Keyboard) { }
...
this.keyboard.onKeyboardShow().subscribe(() => {
   console.log("onKeyboardShow");
});
```

**Comment by EddyVerbruggen** [comment]
Thx!
