### ISSUE TITLE
Question: still maintained ? 

### ISSUE THREAD

**Issue by HartHerbert** [EddyVerbruggen/cordova-plugin-native-keyboard#48]
I am planning to use this plugin in my app and I am wondering if it is still maintained? If yes I would buy it else I wouldn't.

**Comment by EddyVerbruggen** [comment]
I read all comments/issues and try to fix things, but it's not always possible to fix everything. So please make sure it meets your demands before buying it. That's why you can evaluate the plugin before buying it.
