### ISSUE TITLE
dosent get keyboard input in the messenger ( only android ) 

### ISSUE THREAD

**Issue by osterland** [EddyVerbruggen/cordova-plugin-native-keyboard#51]
Hi Folks, 

i dont get any input from the keyboard in the "messenger" anymore. here is a short clip, demonstrating the issue. ( sry folks, im not into gif's -> here is a link to a 20sek video clip https://drive.google.com/open?id=0B5OuS-owJrItSzFWbW1rRmdPdG8  ) 

iOs is running fine btw. 

so I am pretty sure, its sth. specific about this project, but i have absolutly no clue what it could be. Ive removed the cordova plugin and re added it. But without any luck. 

any ideas more than welcome 

greetz

**Comment by osterland** [comment]
Sorry Folks, 

stupid me, set maxChars to 0 ...

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that! 👍
