### ISSUE TITLE
iOS 11, it's not working anymore

### ISSUE THREAD

**Issue by Stefano1964** [EddyVerbruggen/cordova-plugin-native-keyboard#55]
Latest cordova 4.5.0, iOS 11 GM, xCode GM, the messanger is showing but the interface buttons and textarea are not responding.

**Comment by Textras** [comment]
the 'messenger'? Can you click to go inFocus? Sounds like no. What component of those did you upgrade most recently?

**Comment by Stefano1964** [comment]
I cant get focus, the left and right button dont fire the events, no console errors, i have the same problem before upgrading to cordova ios 4.5.0 (also tested iOS 11 / xCode 9), it seem related to iOS 11. It build ok. Before was working like a charm (iOS10.3.3 xCode 8.3.3). If i open the messanger with showKeyboard: true then i can write into the text textbox, bot the left and right button dont fire events.

**Comment by Stefano1964** [comment]
It's seems to be a layout constraints problem, "Unable to simultaneously satisfy constraints"...

**Comment by EddyVerbruggen** [comment]
Thanks for reporting and confirming this issue!

It's indeed an iOS 11 change that breaks the plugin - I've fixed it in 1.4.6. Please give it a spin and let me know if this indeed solves the issue.

**Comment by Stefano1964** [comment]
Hi Eddy, now it's working again, thanks a lot (tested on WKWebview). The only thing now is that on iPhone X (simulator off course) the toolbar is opened at the very bottom overlapping the soft home botton, how can we solve this?

**Comment by EddyVerbruggen** [comment]
Thanks for testing it so quickly. 

Luckily it will be a while before iPhone X is used in the wild and I’m sure lots of apps (native and hybrid) will need to find fixes for this issue so let’s keep an eye out.
