### ISSUE TITLE
Supress predecitive text bar on Android

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/cordova-plugin-native-keyboard#56]
It just gets in the way, and I've had multiple users ask to get rid of it so here we go.

**Comment by EddyVerbruggen** [comment]
@svzi yep, I think that would be possible (by default it will be suppressed).

**Comment by svzi** [comment]
That would be pretty awesome. :+1:  Until then, the plugin is currently useless for me (which makes me sad, because the plugin really look and feels great except for that particular issue).

**Comment by EddyVerbruggen** [comment]
I hope the now-published 1.5.3 version helps :)
See `suppressSuggestions` in the readme for details.

Note that I didn't have time to test it, so please give it a spin. You may need to remove the platforms/android folder to make sure the updated library is applied correctly.

**Comment by svzi** [comment]
Thank you very much. :+1: I appreciate your strong support!

For my use case it works perfectly with `supressSuggestions: false`, but I also tried with `supressSuggestions: true` and that also shows suggestions. So it seems you did miss something.

**Comment by EddyVerbruggen** [comment]
Haha, that's weird. Thanks for the heads-up!
