### ISSUE TITLE
Not compiling on iOS. Error 65.

### ISSUE THREAD

**Issue by MasTeh** [EddyVerbruggen/cordova-plugin-native-keyboard#59]
I can't complile on iOS. Error 65. Who know why i can fix it?

**Comment by bear1030** [comment]
I am getting this error as well. Is there any solution?

**Comment by EddyVerbruggen** [comment]
I'm not sure what the problem is actually.. I just did this and there was no error (latest Xcode):

```
cordova create nativekeyboardtest2
cd nativekeyboardtest2
cordova platform add ios
cordova plugin add cordova-plugin-native-keyboard
cordova build ios
```

**Comment by MasTeh** [comment]
I can't install. My cordova and xcode is latest version.

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/HelloCordova.app/HelloCordova normal x86_64
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/admin/Documents/nativekeyboard/platforms/ios/cordova/build-debug.xcconfig,-workspace,HelloCordova.xcworkspace,-scheme,HelloCordova,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Users/admin/Documents/nativekeyboard/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/admin/Documents/nativekeyboard/platforms/ios/build/sharedpch

**Comment by EddyVerbruggen** [comment]
Just built and ran fine with the latest Cordova on iPhone X. Not much I can do then.
