### ISSUE TITLE
Cordova application crashes on iOS 11 for fileReader.readAsText(file) method

### ISSUE THREAD

**Issue by naveenhg** [EddyVerbruggen/cordova-plugin-native-keyboard#64]
I've my iPad application working fine with iOS 8,9 and 10. But it crashes in the statement fileReader.readAsText(file) for iOS 11.

Is there a new version of Cordova for iOS 11 to fix this issue?

**Comment by EddyVerbruggen** [comment]
I don't think this is plugin related as that piece of code isn't part of the plugin. Also, just tried a new app with the latest Cordova bits and all worked fine.
