### ISSUE TITLE
How did you do the screenshots?

### ISSUE THREAD

**Issue by john-doherty** [EddyVerbruggen/cordova-plugin-native-keyboard#65]
Hello.

I appreciate you're busy so please don't rush to answer this. I'm just curious, what steps did you take to produce the animated gif screenshots included in the project?

Cheers,

John

**Comment by EddyVerbruggen** [comment]
Hi John,

Those animated gifs of iOS/Android emulators were captured from my desktop with https://getkap.co/

I may be wrong and captured them with Quicktime (it has a built in screen recording feature) and postprocessed them with https://ezgif.com/optimize

**Comment by john-doherty** [comment]
Hi Eddy, that's great. Thank you for the info!
