### ISSUE TITLE
iPhone X - iOS 11.2 - position of the messenger (textarea)

### ISSUE THREAD

**Issue by idroxid** [EddyVerbruggen/cordova-plugin-native-keyboard#68]
Hi,

I'm testing the plugin as I found it in the official documentation of ionic!
I'm pretty sure I will use it for my app, but I need to fix this before.

The thing is that when I run it on **iPhone X**, the position of the messenger (when the keyboard is closed) is not really convenient. I mean, it's placed at the really bottom of the screen, below the "home bar". On the other iPhone models, this is not an issue as it's the position we are used to find this kind of textareas.

![messenger-bottom](https://user-images.githubusercontent.com/5407252/35462564-c12f85c4-02ec-11e8-8d25-53aba93cac01.png)

Is this something you can fix ?

Many thanks!

**Comment by idroxid** [comment]
Hi @EddyVerbruggen,
Is the project still maintained ? I mean, it's in the official ionic documentation, and we're supposed to pay for it. So, if it's not maintained, we just need to know about it...
Please let me/us know.
Many thanks for the good work and for the news.
-- Oh, yes. What about contributing to the project ? There is no pull requests, but some forks out there.
Any solution is good for me. I just want to be sure you're still working on the thing or not :)
Cheers! 👍

**Comment by EddyVerbruggen** [comment]
It is maintained, but this was a pretty hard nut to crack actually.

Please update to 1.5.0 and (for iPhone X), add [`viewport-fit=cover` to your viewport](https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/blob/84fa7ce962f1b56cc71b1d1f2454c46ba3b8aca7/demo/index.html#L6).
