### ISSUE TITLE
Side menu

### ISSUE THREAD

**Issue by geshub** [EddyVerbruggen/cordova-plugin-native-keyboard#77]
Hi,

Is it possible to integrate it with a side menu app ?

**Comment by geshub** [comment]
Hi Eddy,

I mean the input seems to overlap the side menu when opened, is there any way to avoid this ?

**Comment by EddyVerbruggen** [comment]
can you share a screenshot/video?

**Comment by geshub** [comment]
Hi Eddy,

I'll setup another test and have some screenshot done, 
but it's only that the side menu doesn't open above the native input.
