### ISSUE TITLE
No text-predictions on Android with SwiftKey

### ISSUE THREAD

**Issue by svzi** [EddyVerbruggen/cordova-plugin-native-keyboard#83]
**What you're trying to accomplish**
Use text-predictions with the Android SwiftKey keyboard with this plugin. It does not work in my project, so I decided to try the demo app for cordova-plugin-native-keyboard and it didn't work as well on my phones.

**What did you do**
I created a blank project and added the plugins as instructed by the Readme then coppied over the contents of demo/index.html to my www folder. I then used cordova platform add android and cordova run android to sideload the app onto my phone.

**What you expected to happen**
Using text-predictions while I type as I normally do with SwiftKey as my default keyboard.

**What actually happened**
No text-predictions are shown with the SwiftKey keyboard. When I switched back to Gboard, the factory installed keyboard for my phone, the text-predictions worked. All other apps, at least all apps I know about, use text-predictions with SwiftKey. I wouldn't use SwiftKey for years if that keyboard didn't support text-predictions...

I've prepared a short video:
https://streamable.com/z8dpl

This isue may also somewhat related to https://github.com/EddyVerbruggen/cordova-plugin-native-keyboard/issues/80, at least it's both SwiftKey. And with over 100.000.000 installs for SwiftKey, I guess it's somewhat popular among Android users and no niche app.

**Cordova Information**
```
Node version: v6.11.4

Cordova version: 8.0.0

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-native-keyboard" spec="^1.5.5">
        <variable name="LICENSE" value="9e34376354dcbe8187a1" />
    </plugin>
    <plugin name="cordova-plugin-console" spec="^1.1.0" />
    <plugin name="cordova-plugin-actionsheet" spec="^2.3.3" />
    <engine name="ios" spec="^4.5.4" />
    <engine name="android" spec="^6.4.0" />
</widget>


Plugins:

cordova-plugin-actionsheet,cordova-plugin-console,cordova-plugin-native-keyboard,cordova-plugin-whitelist

Android platform:

*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Running /usr/local/Caskroom/android-sdk/3859397/tools/bin/avdmanager list target

Available Android targets:==============] 100% Fetch remote repository...
----------
id: 1 or "android-25"
     Name: Android API 25
     Type: Platform
     API level: 25
     Revision: 3

iOS platform:

Xcode 9.4
Build version 9F1027a

```

**Comment by EddyVerbruggen** [comment]
Wasn't this solved with #56?

**Comment by svzi** [comment]
@EddyVerbruggen Any update on this?

**Comment by EddyVerbruggen** [comment]
Hi @svzi, thanks for the detailed bug report! I had to do some trial and error to figure out why SwiftKey didn't play nice, but it seems like it's sorted. Just upgrade to 1.5.6 and set `suppressSuggestions: false` and both predictions and swiping should work.

**Comment by gregavola** [comment]
@EddyVerbruggen with `false` selected, I get no predictions - and no swiping with SwiftKey for some reason.

**Comment by EddyVerbruggen** [comment]
@gregavola On what device etc?

I’m trying to enjoy a little vacation so don’t expect swift answers..

**Comment by gregavola** [comment]
So far it’s every device I’ve tested it upon.  Nexus 5, emulator. I’ll get you more specifics.
