### ISSUE TITLE
Bug with cordova-plugin-ionic-keyboard

### ISSUE THREAD

**Issue by smxdevst** [EddyVerbruggen/cordova-plugin-native-keyboard#88]
https://github.com/ionic-team/ionic-native/blob/master/CHANGELOG.md

Ionic on 2018-09-25  switched from `ionic-plugin-keyboard` to `cordova-plugin-ionic-keyboard`. However, this plugin breaks with `cordova-plugin-ionic-keyboard`

![img_f88be3549fac-1](https://user-images.githubusercontent.com/13336971/46508306-ddfa1500-c7f1-11e8-8dc9-344c53285395.jpeg)

Ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 24 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v8.9.4 (/usr/local/bin/node)
   npm        : 6.0.1
   OS         : macOS
   Xcode      : Xcode 9.4.1 Build version 9F2000

```

**Comment by ActNotSign** [comment]
i fixed it,  u can take it in  pull request.
